
## PC1

nombre:Leonarddo Carlos López Solis
código: 20232345

This code will give you the data you will use for this PC:

In [91]:
# read web table into pandas DF
import pandas as pd

co2Link='https://docs.google.com/spreadsheets/d/e/2PACX-1vRXjfxeKHQBBCh_oHP-D6RIHEX4eduLjydHb6ZGsU4jo0IK0KKQSoYX_X1FGssC_9hnqCgjKN0K4AVf/pub?gid=775098192&single=true&output=csv'
carbon=pd.read_csv(co2Link)

In [105]:
# here it is:
carbon

,name,metric_tonnes_of_CO2,date_of_information,ranking,region
0,China,1.219600e+10,2023,1,East and Southeast Asia
1,United States,4.795000e+09,2023,2,North America
2,India,2.821000e+09,2023,3,South Asia
3,Russia,1.844000e+09,2023,4,Central Asia
4,Japan,9.602300e+08,2023,5,East and Southeast Asia
...,...,...,...,...,...
211,Falkland Islands (Islas Malvinas),3.600000e+01,2023,212,South America
212,Montserrat,2.400000e+01,2023,213,Central America and the Caribbean
213,Antarctica,1.500000e+01,2023,214,Antarctica
214,"Saint Helena, Ascension, and Tristan da Cunha",1.200000e+01,2023,215,Africa
215,Niue,9.000000e+00,2023,216,Australia and Oceania

As you see, some columns have space, which should be deleted:

In [106]:
# also
carbon.columns

Index(['name', 'metric_tonnes_of_CO2', 'date_of_information', 'ranking',
       'region'],
      dtype='object')

In [107]:
# Like this
carbon.rename(columns={'metric tonnes of CO2':'metric_tonnes_of_CO2'},inplace=True)

# see
carbon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  216 non-null    object
 1   metric_tonnes_of_CO2  216 non-null    float64
 2   date_of_information   216 non-null    int64
 3   ranking               216 non-null    int64
 4   region                216 non-null    object
dtypes: float64(1), int64(2), object(2)
memory usage: 8.6+ KB

You always make a copy:

In [108]:
carbon_copy=carbon.copy()

## Questions

Complete the tasks requested using **carbon_copy**:

1. Keep all the columns but _Ranking_:
    * Tip: use [drop](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html), [loc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html), and [iloc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html) for the same purpose (three ways to accomplish the task).

2. Find the country with the minimum CO2 emission in the world.

3. Find the country with the minimum CO2 emission per Region.

4. Create a new column by keeping the square root of the the original CO2  column.

5. Compute the average of CO2. Then, create a new column. This new column is
the original CO2 minus the average computed.

You have changed **carbon_copy**, now save it as a file like this:

In [109]:
#carbon_copy.to_csv("carbon_copy.csv",index=False)

**First task**

In [110]:
carbon_copy

,name,metric_tonnes_of_CO2,date_of_information,ranking,region
0,China,1.219600e+10,2023,1,East and Southeast Asia
1,United States,4.795000e+09,2023,2,North America
2,India,2.821000e+09,2023,3,South Asia
3,Russia,1.844000e+09,2023,4,Central Asia
4,Japan,9.602300e+08,2023,5,East and Southeast Asia
...,...,...,...,...,...
211,Falkland Islands (Islas Malvinas),3.600000e+01,2023,212,South America
212,Montserrat,2.400000e+01,2023,213,Central America and the Caribbean
213,Antarctica,1.500000e+01,2023,214,Antarctica
214,"Saint Helena, Ascension, and Tristan da Cunha",1.200000e+01,2023,215,Africa
215,Niue,9.000000e+00,2023,216,Australia and Oceania

In [111]:
#En primer lugar, creamos una lista que indique las columnas a eliminar
deletColums=['ranking']
#Eliminamos esa columna con la función drop
#y la eliminamoes directamente en el data frame carbon_copy con comando inplace=True
carbon_copy.drop(columns=deletColums,inplace=True)
carbon_copy

,name,metric_tonnes_of_CO2,date_of_information,region
0,China,1.219600e+10,2023,East and Southeast Asia
1,United States,4.795000e+09,2023,North America
2,India,2.821000e+09,2023,South Asia
3,Russia,1.844000e+09,2023,Central Asia
4,Japan,9.602300e+08,2023,East and Southeast Asia
...,...,...,...,...
211,Falkland Islands (Islas Malvinas),3.600000e+01,2023,South America
212,Montserrat,2.400000e+01,2023,Central America and the Caribbean
213,Antarctica,1.500000e+01,2023,Antarctica
214,"Saint Helena, Ascension, and Tristan da Cunha",1.200000e+01,2023,Africa
215,Niue,9.000000e+00,2023,Australia and Oceania

**Second task**

In [112]:
#Mostramos que país emite la menor cantidad de CO2}
carbon_copy[carbon_copy.metric_tonnes_of_CO2==min(carbon_copy.metric_tonnes_of_CO2)].iloc[0,0]

'Niue'

El país con las menores emisiones de CO2 es Niue

**Third task**

In [113]:
#Buscamos cuales son todas las categorías de región
carbon_copy.region.unique()

array(['East and Southeast Asia', 'North America', 'South Asia',
       'Central Asia', 'Middle East', 'Europe', 'Africa', 'South America',
       'Australia and Oceania', 'Central America and the Caribbean',
       'Antarctica'], dtype=object)

In [114]:
#El país con menor cantidad de emisiones de East and Southeast Asia
carbon_copy[carbon_copy.region=='East and Southeast Asia'].sort_values(by='metric_tonnes_of_CO2', ascending=True).iloc[0,0]

'Timor-Leste'

In [115]:
#El país con menor cantidad de emisiones de North America
carbon_copy[carbon_copy.region=='North America'].sort_values(by='metric_tonnes_of_CO2', ascending=True).iloc[0,0]

'Saint Pierre and Miquelon'

In [116]:
#El país con menor cantidad de emisiones de South Asia
carbon_copy[carbon_copy.region=='South Asia'].sort_values(by='metric_tonnes_of_CO2', ascending=True).iloc[0,0]

'Bhutan'

In [117]:
#El país con menor cantidad de emisiones de Central Asia
carbon_copy[carbon_copy.region=='Central Asia'].sort_values(by='metric_tonnes_of_CO2', ascending=True).iloc[0,0]

'Armenia'

In [118]:
#El país con menor cantidad de emisiones de Middle East
carbon_copy[carbon_copy.region=='Middle East'].sort_values(by='metric_tonnes_of_CO2', ascending=True).iloc[0,0]

'West Bank'

In [119]:
#El país con menor cantidad de emisiones de Europe
carbon_copy[carbon_copy.region=='Europe'].sort_values(by='metric_tonnes_of_CO2', ascending=True).iloc[0,0]

'Faroe Islands'

In [120]:
#El país con menor cantidad de emisiones de Africa
carbon_copy[carbon_copy.region=='Africa'].sort_values(by='metric_tonnes_of_CO2', ascending=True).iloc[0,0]

'Saint Helena, Ascension, and Tristan da Cunha'

In [121]:
#El país con menor cantidad de emisiones de South America
carbon_copy[carbon_copy.region=='South America'].sort_values(by='metric_tonnes_of_CO2', ascending=True).iloc[0,0]

'Falkland Islands (Islas Malvinas)'

In [122]:
#El país con menor cantidad de emisiones de Australia and Oceania
carbon_copy[carbon_copy.region=='Australia and Oceania'].sort_values(by='metric_tonnes_of_CO2', ascending=True).iloc[0,0]

'Niue'

In [123]:
#El país con menor cantidad de emisiones de Central America and the Caribbean
carbon_copy[carbon_copy.region=='Central America and the Caribbean'].sort_values(by='metric_tonnes_of_CO2', ascending=True).iloc[0,0]

'Montserrat'

In [124]:
#El país con menor cantidad de emisiones de Antarctica
carbon_copy[carbon_copy.region=='Antarctica'].sort_values(by='metric_tonnes_of_CO2', ascending=True).iloc[0,0]

'Antarctica'

**Fourth task**

In [125]:
#Creamos una lista con la raíz cuadrada de las emisiones de  CO2
carbon_root_of_metric_tonnes_CO2=carbon_copy.metric_tonnes_of_CO2.apply(lambda x: x**0.5)
carbon_root_of_metric_tonnes_CO2

0      110435.501538
1       69245.938509
2       53113.086900
3       42941.821107
4       30987.578156
           ...
211         6.000000
212         4.898979
213         3.872983
214         3.464102
215         3.000000
Name: metric_tonnes_of_CO2, Length: 216, dtype: float64

In [127]:
#agregamos una nueva columna carbon_root_of_metric_tonnes_CO2
carbon_copy['root_of_metric_tonnes_of_CO2']=carbon_root_of_metric_tonnes_CO2
carbon_copy

,name,metric_tonnes_of_CO2,date_of_information,region,root_of_metric_tonnes_of_CO2
0,China,1.219600e+10,2023,East and Southeast Asia,110435.501538
1,United States,4.795000e+09,2023,North America,69245.938509
2,India,2.821000e+09,2023,South Asia,53113.086900
3,Russia,1.844000e+09,2023,Central Asia,42941.821107
4,Japan,9.602300e+08,2023,East and Southeast Asia,30987.578156
...,...,...,...,...,...
211,Falkland Islands (Islas Malvinas),3.600000e+01,2023,South America,6.000000
212,Montserrat,2.400000e+01,2023,Central America and the Caribbean,4.898979
213,Antarctica,1.500000e+01,2023,Antarctica,3.872983
214,"Saint Helena, Ascension, and Tristan da Cunha",1.200000e+01,2023,Africa,3.464102
215,Niue,9.000000e+00,2023,Australia and Oceania,3.000000


**Fifth Task**

In [128]:
#Calculamos el promedio de las medidas de toneladas de CO2
carbon_copy.metric_tonnes_of_CO2.mean()

np.float64(171564562.3412037)

In [129]:
#Creamos una nueva columna en donde se reste las medidas de toneladas de CO2 con el promedio
carbon_copy['metric_tonnes_of_CO2_minus_average']=carbon_copy.metric_tonnes_of_CO2-carbon_copy.metric_tonnes_of_CO2.mean()
carbon_copy

,name,metric_tonnes_of_CO2,date_of_information,region,root_of_metric_tonnes_of_CO2,metric_tonnes_of_CO2_minus_average
0,China,1.219600e+10,2023,East and Southeast Asia,110435.501538,1.202444e+10
1,United States,4.795000e+09,2023,North America,69245.938509,4.623435e+09
2,India,2.821000e+09,2023,South Asia,53113.086900,2.649435e+09
3,Russia,1.844000e+09,2023,Central Asia,42941.821107,1.672435e+09
4,Japan,9.602300e+08,2023,East and Southeast Asia,30987.578156,7.886654e+08
...,...,...,...,...,...,...
211,Falkland Islands (Islas Malvinas),3.600000e+01,2023,South America,6.000000,-1.715645e+08
212,Montserrat,2.400000e+01,2023,Central America and the Caribbean,4.898979,-1.715645e+08
213,Antarctica,1.500000e+01,2023,Antarctica,3.872983,-1.715645e+08
214,"Saint Helena, Ascension, and Tristan da Cunha",1.200000e+01,2023,Africa,3.464102,-1.715646e+08
215,Niue,9.000000e+00,2023,Australia and Oceania,3.000000,-1.715646e+08

Guardamos el archivo como se nos indica

In [131]:
carbon_copy.to_csv("carbon_copy.csv",index=False)